"""
Swarm State Definition.
Shared state for the Multi-Agent Graph.
"""
from typing import List, Dict, Optional, TypedDict
from pydantic import BaseModel

from ...core.models.events import EventNode
from ...core.models.evidence import Evidence
from ...core.models.claim import Claim

class SectionPlan(BaseModel):
    """Plan for a single report section."""
    id: str
    title: str
    description: str
    assigned_event_ids: List[str] = []
    assigned_claim_ids: List[str] = []
    disputed_claim_ids: List[str] = [] # Point 3: Conflicts
    conflict_policy: str = "present_both" # "present_both" | "no_conclusion"

class ReportOutline(BaseModel):
    """Full Report Outline generated by Director."""
    title: str
    introduction: str
    sections: List[SectionPlan]
    conclusion: str

class SwarmState(TypedDict):
    """
    Shared State for Layer 2 Swarm.
    """
    # Inputs
    topic: str
    events: List[EventNode]
    claims: List[Claim]
    evidences: List[Evidence]
    
    # Process State
    outline: Optional[ReportOutline]
    current_section_idx: int
    draft_sections: Dict[str, str] # section_id -> markdown content
    
    # Revision State
    critique_feedback: Optional[str]
    revision_count: int
    global_revision_count: int
    
    # Output
    final_report: str
    open_questions: List[str]
